--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/lenlenlL6/BitcoinAPI
build-by-default: true
branches:
- main
projects:
  BitcoinAPI:
    path: ""
    icon: "20211031_195026.jpg"
...
