name: BitcoinAPI
main: BitcoinAPI\Bitcoin
author: pmmdst
api: 3.0.0
version: 0.0.1

commands:
  mybitcoin:
    description: Show Your Bitcoin
    permission: mybitcoin.pmmdst
  setbitcoin:
    description: Set Player Bitcoin
    permission: setbitcoin.pmmdst
  topbitcoin:
    description: Top Bitcoin Of The Server
    permission: topbitcoin.pmmdst
permissions:
  mybitcoin.pmmdst:
    default: true
  setbitcoin.pmmdst:
    description: Allow Set Player Bitcoin
    default: op
  topbitcoin.pmmdst:
    default: true
